### ISSUE TITLE
'preferences.HamsterSpinButton'-Adjustment should validate values to be int

### ISSUE THREAD

**Issue by elbenfreund** [projecthamster/hamster-gtk#114]
Our spin button deliberately deals only with `int` values for `min`, `max` and `step`. This should be validated in its `__int__` method.

**Comment by jtojnar** [comment]
As for the `configure` method, I vaguely recall some problems with `climb_rate` but I am not able to replicate anything.

**Comment by elbenfreund** [comment]
As it is not clear at all why it would be needed to limit ourselfs to ints here the issue will be rejected as it is right now. Please feel free to reopen once there is an actual use case...
