### ISSUE TITLE
Rearrange preferences into tabs

### ISSUE THREAD

**Issue by jtojnar** [projecthamster/hamster-gtk#118]
Use GtkStack to rearrange preferences into tabs.

Concept:

![hamster-preferences](https://cloud.githubusercontent.com/assets/705123/19083025/cd2863f6-8a60-11e6-9848-55860ee9caac.png)

**Comment by elbenfreund** [comment]
Please not that [`Gtk.Stack`](http://lazka.github.io/pgi-docs/Gtk-3.0/classes/Stack.html#class-details) is considered best practice for modern GTK3 applications.

**Comment by jtojnar** [comment]
I initially wanted to use `GtkStack` but then I noticed Nautilus uses `GtkNotebook`.

**Comment by elbenfreund** [comment]
I for the life of me can not find the reference that I am sure as hell once had for that, so I can not back this up any further at this point. But  please, before you invest any time lets see what `#gnome-hackers` replies.
If there is no definitive answer, I will prefer `GTK.Stack` and would hate to see any effort of yours go to waste.
