### ISSUE TITLE
Import/preserve data from current stable version?

### ISSUE THREAD

**Issue by jefferyto** [projecthamster/hamster-gtk#123]
Apologies if this information is available somewhere already; I've looked on the new project site and in the various repo READMEs but I haven't seen this mentioned. (The dev mailing list archives is private to list members only so I can't search it or feel comfortable joining just to ask this question.)

I am using the current stable version (from the [Ubuntu PPA](https://launchpad.net/~dylanmccall/+archive/ubuntu/hamster-time-tracker-git-stable) so it's probably not even the latest stable version), and will wait until the rewrite has stabilized a bit before switching.

Will the rewrite version be able to preserve or import data from the current stable version? This data is important for me and I hope to be able to continue accessing it in the future.

I think it would be nice for current Hamster users if this answer is included somewhere prominent as well.

Thanks for picking up development for this useful tool :smile:

**Comment by jtojnar** [comment]
It took me a while to recall where I read it, it was on the [mailing lists](http://lists.projecthamster.org/private.cgi/hamster-dev-projecthamster.org/2016-July/000006.html):

> > Quick question: 
> > 
> > Can I use this new version as the GUI for my already existing database
> > created by the old hamster?
> 
> No you can not. The plan right now is to not support a seamless
> continuation of the old database as our layout and assumptions about the
> data structure are too different. We are much stricter than legacy
> hamster as we do not allow facts without end time. So that would mean we
> would have to deal with migrating all of those invalidated cases,
> provide a UI for it etc... Also, the old db carries legacy fragments
> that are never used at all and seem to be left overs from the last 7 years.
> 
> Because using your old data is of cause a solid requirement we will use
> 'legacy hamster's ability to export your data as csv to allow a painless
> import from it. But this is not implemented as of now. And 'hamster-gtk'
> should not be used on any real dataset anyway at this stage. :)

So yes, imports should be possible but it is not implemented yet.

**Comment by elbenfreund** [comment]
Hi @jefferyto , first of all: Thank you for being a paragon issue tracker user :) And my apologies for making it so hard/impossible to find this bit of information. As of now the mailing list archive is public now. I also agree that this information should be placed somewhere more visible for the time being. This is addressed by #130 

With regards to your actual question, @jtojnar answer is correct. There will be a way to import data that still constitutes valid 'facts' (that is has a start and end time). We have however not decided on how this will be implemented nor what to do with legacy 'facts' that do not have an end time.
If you are interested in this general issue, please feel free to watch the [epic issue for `hamster-lib`](https://projecthamster.atlassian.net/browse/LIB-12) that covers all things relevant.

**Comment by jefferyto** [comment]
Thanks @jtojnar and @elbenfreund - I'll close this in favour of #130.
