### ISSUE TITLE
Use of backports namespace

### ISSUE THREAD

**Issue by jtojnar** [projecthamster/hamster-gtk#124]
For compatibility with Python 2, we are using [configparser](https://pypi.python.org/pypi/configparser) package. It is also used, however, for Python 3, where it is not necessary.

> To use the `configparser` backport instead of the built-in version on both Python 2 and Python 3, simply import it explicitly as a backport:
> 
> ```
> from backports import configparser
> ```
> 
> If you’d like to use the backport on Python 2 and the built-in version on Python 3, use that invocation instead:
> 
> ```
> import configparser
> ```

Why not use the second import? It would make packaging easier on systems that do not provide `python3-configparser` package. This is how the packaging looks like now: [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-hamster-lib).

**Comment by elbenfreund** [comment]
At the time, using backports seemed the cleaner and more straight forward solution as it makes sure the same package is used with python 2 and 3. i do not have any general objections to using the standard configparser module under python3 if there are no side effects.
If we decide to go down that route, a corresponding issue should be created with `hamster-lib`.

**Comment by elbenfreund** [comment]
An issue with [``hamster-lib``](https://projecthamster.atlassian.net/browse/LIB-236) has been created.

**Comment by elbenfreund** [comment]
Closing as this has been solved in ``hamster-lib==0.13.0``

**Comment by jtojnar** [comment]
This seems to be still true in `hamster-gtk`, try grepping for backports.
