### ISSUE TITLE
Orphans in documentation

### ISSUE THREAD

**Issue by jtojnar** [projecthamster/hamster-gtk#127]
`modules` and `packaging` pages are not linked anywhere in the documentation, resulting in following warning:

``` shell
checking consistency...
hamster-gtk/docs/modules.rst:: WARNING: document isn't included in any toctree
hamster-gtk/docs/packaging.rst:: WARNING: document isn't included in any toctree
done
```

**Comment by elbenfreund** [comment]
As you are probably aware, I did not spend too much time bringing `hamster-gtk`s autodocs up to speed properly so far. This was not deliberate and merely due to lack of time. I will be happy for any improvement :)
