### ISSUE TITLE
Typo in the README File

### ISSUE THREAD

**Issue by aabi01** [projecthamster/hamster-gtk#129]
There is a typo in the first paragraph of README File

"IMPORTANT At this early stage hamster-gtk is pre-alpha software. As such you are very welcome to take it our for a spin and submit feedback, however you should not rely on it to work properly and most certainly you should not use it **in an production** environment! You have been warned."

**Comment by elbenfreund** [comment]
Thank you for reporting this :+1:

**Comment by eyaffe** [comment]
Hi, this was my first time doing this, so editing the README seemed harmless enough! Hope I did everything right.
