### ISSUE TITLE
It should be possible to "start tracking" by pressing enter after entering text

### ISSUE THREAD

**Issue by elbenfreund** [projecthamster/hamster-gtk#137]
in order to make tracking fast an convenient it would be nice to be able to just press enter when entering the *raw fact* while the text entry still does have the focus.

**Comment by jtojnar** [comment]
How does this differ from #69?

**Comment by elbenfreund** [comment]
It doesn't. I was simply not following my own advise checking for dupes. Thanks for the hint.
