### ISSUE TITLE
could you provide compiled packages for different distros?

### ISSUE THREAD

**Issue by trenkert** [projecthamster/hamster-gtk#151]
It makes it so much easier to get bug reports, feedback, and new devs if there is a deb/rpm package that users can quickly install and test.

**Comment by elbenfreund** [comment]
This is definitly something we would like :) Right now it is still a bit early do address distro packaging and I guess it will be up to additional contributors to help out with specific packaging once it makes sense.

With regards to "quickly install and test" however, please note that the entire project fully supports pythons packageing best practices and can be installed as easy as ``pip install hamster-gtk`` or ``pip install -e .``

**Comment by trenkert** [comment]
Ah, ok, I haven't seen this option. Thanks!

**Comment by elbenfreund** [comment]
hehe. did something go wrong with your quote? :)

**Comment by trenkert** [comment]
Indeed 😊 too many comments.
