### ISSUE TITLE
How to run it on the mac

### ISSUE THREAD

**Issue by 0xErnie** [projecthamster/hamster-gtk#179]
I used hamster on Linux and really liked it, now I have to use OS X.
What do I have to install?

First I got "ImportError: No module named gi" after installing "pygobject3" the error is "ValueError: Namespace Gdk not available for version 3.0".

**Comment by jtojnar** [comment]
Also try `brew install gtk+3`

**Comment by 0xErnie** [comment]
Thank you 👍 
![hamster](https://cloud.githubusercontent.com/assets/234937/24869162/990eba20-1e12-11e7-8b47-22633ba3e162.png)

**Comment by jtojnar** [comment]
It looks worse than I thought. In the future, it would be nice to have a native Cocoa client, instead of this abomination.

**Comment by vpistis** [comment]
Maybe I have the same problem, pip (and brew) don't finds `python3-gi`. I used the provided `setup.py` into a virtualenv for python 3, the error is: 
```
    import gi
ImportError: No module named 'gi'
```

Please if possible, tell me the exact dependencies for MacOS with python3.

Thank you so much

**Comment by jtojnar** [comment]
@vpistis Did you call `togglesitepackages`?

**Comment by vpistis** [comment]
@jtojnar  yes!

**Comment by vpistis** [comment]
I think some problem was due to the conflict python3 macos native and the brew python3. Now I have correctly linked the python3 from brew to my virtualenv, but now appears an error that seems a bug :)
```
File "/Users/user/.virtualenvs/hamster-gtk/lib/python3.6/site-packages/hamster_lib-0.13.0-py3.6.egg/hamster_lib/helpers/config_helpers.py", line 155, in get_config_path
    return os.path.join(appdirs.user_config_dir, file_name)
AttributeError: 'str' object has no attribute 'user_config_dir'
```

**Comment by jtojnar** [comment]
@vpistis That looks like #182, patch pending.

**Comment by vpistis** [comment]
ok thanx

**Comment by elbenfreund** [comment]
This should be fixed in develop now. @vpistis can you confirm?

**Comment by vpistis** [comment]
No, hamster-lib==0.13.1 not solve, same error.
It run only with hamster-lib==0.12.
Hamster-gtk is updated at this commit: d2e87f406cbae20d728e50275f65318b55064314

**Comment by elbenfreund** [comment]
just for completeness sake, can you post the error message with ``hamster-lib==0.13.1`` please?

**Comment by vpistis** [comment]
yes here it is:
```python
(hamster-gtk)vpistis@vpistisMacBookAir /D/hamster-gtk> hamster-gtk
Traceback (most recent call last):
  File "/Users/vpistis/.virtualenvs/hamster-gtk/bin/hamster-gtk", line 11, in <module>
    load_entry_point('hamster-gtk==0.11.0', 'gui_scripts', 'hamster-gtk')()
  File "/Users/vpistis/.virtualenvs/hamster-gtk/lib/python3.6/site-packages/hamster_gtk/hamster_gtk.py", line 389, in _main
    app = HamsterGTK()
  File "/Users/vpistis/.virtualenvs/hamster-gtk/lib/python3.6/site-packages/hamster_gtk/hamster_gtk.py", line 181, in __init__
    self._config = self._reload_config()
  File "/Users/vpistis/.virtualenvs/hamster-gtk/lib/python3.6/site-packages/hamster_gtk/hamster_gtk.py", line 238, in _reload_config
    config = self._get_config_from_file()
  File "/Users/vpistis/.virtualenvs/hamster-gtk/lib/python3.6/site-packages/hamster_gtk/hamster_gtk.py", line 383, in _get_config_from_file
    cp_instance = get_config_instance(get_fallback(), 'hamster-gtk', 'hamster-gtk.conf')
  File "/Users/vpistis/.virtualenvs/hamster-gtk/lib/python3.6/site-packages/hamster_gtk/helpers.py", line 127, in get_config_instance
    path = config_helpers.get_config_path(app_name, file_name)
  File "/Users/vpistis/.virtualenvs/hamster-gtk/lib/python3.6/site-packages/hamster_lib/helpers/config_helpers.py", line 155, in get_config_path
    return os.path.join(appdirs.user_config_dir, file_name)
AttributeError: 'str' object has no attribute 'user_config_dir'
```

**Comment by elbenfreund** [comment]
I do not now how or why as I am not familiar with the MacOS setup, but you are *not* using the latest ``develop`` version.

if you look at the 5th line from the bottom, you see ``hamster-gtk`` call ``get_config_instance``.
This helper method [no longer exists](https://github.com/projecthamster/hamster-gtk/blob/develop/hamster_gtk/helpers.py#L127).

Please update your ``hamster-gtk`` and try again.

**Comment by vpistis** [comment]
ok...i'm sorry, my problem was due to a conflict with another hamster-gtk installation
This issue is solved for me :)
Tx

**Comment by elbenfreund** [comment]
Great to hear.
Do you think you could help us providing a proper "how to run hamster-gtk on MacOs" instruction? We (and I am sure others) would be most grateful :)
