### ISSUE TITLE
Do not install tests

### ISSUE THREAD

**Issue by jtojnar** [projecthamster/hamster-gtk#189]
When installing the app using `python setup.py install --root="${pkgdir}" --optimize=1`, the tests will also be installed, even when calling `sed "s/find_packages()/find_packages(exclude=['tests'])/" -i setup.py` beforehand.

This may lead to a conflict when installing another app that contains the same file (e.g. `/usr/lib/python3.6/site-packages/tests/helpers/__init__.py`).

Default build log: https://paste.gnome.org/pgfkanom1
Build log with tests excluded and removed from `MANIFEST.in`: https://paste.gnome.org/pv04lfs9l

**Comment by jtojnar** [comment]
Apparently `tests*` needs to be excluded from `find_packages`:

https://packaging.python.org/tutorials/distributing-packages/?highlight=tests#packages

Now, can we make that default?

**Comment by elbenfreund** [comment]
yes. so to be clear: the reason exclude did not work before was becaue of ``test*`` vs ``tests``?.

**Comment by jtojnar** [comment]
Yes

**Comment by jtojnar** [comment]
Yes `tests` → `tests*`
