### ISSUE TITLE
'tests' make target should run with 'xvfb'

### ISSUE THREAD

**Issue by elbenfreund** [projecthamster/hamster-gtk#206]
In order to prevent the testsuite from bleeding through to the developers main session we should use ``xvfb``.

Todo: Use ``xvfb-run`` for ``tests`` make target.

**Comment by jtojnar** [comment]
I still think the pytest plug-in is preferable, since it makes the dependency on Xvfb optional.

Also #95

**Comment by elbenfreund** [comment]
What is the benefit of this optionality?

**Comment by jtojnar** [comment]
I was thinking about platforms not supporting Xvfb like Win or modern Mac OS

**Comment by elbenfreund** [comment]
I see. That seems in fact like a reasonable point. I always disliked its "siltent failure" when ``xvfb`` is not installed which makes it a bit too in-transparent for my taste. I always felt that the simple "warning" shown in the output is far too easy to miss. But this seems not enough to counter your win/maxos concerns.

I will close this issue and it will be just the testing developers responsibility to make sure xvfb is installed and to verify it is beeing used.
