### ISSUE TITLE
Custome elements are tiny on HiDPi

### ISSUE THREAD

**Issue by daniellandau** [projecthamster/hamster-gtk#220]
On the overview some of the elements are extremely small when running under HiDPi.

![kuvakaappaus - 2017-10-05 15-22-05](https://user-images.githubusercontent.com/1044056/31227016-f9fc3a38-a9e0-11e7-9bbe-be1065f504aa.png)

I'm running under gnome-shell in Arch Linux with scaling factor 2.

**Comment by jtojnar** [comment]
What screen is that? I do not remember hamster-gtk having a home button. Are you sure you are not running https://github.com/projecthamster/hamster?

**Comment by daniellandau** [comment]
It seems I am, sorry for the noise.
