### ISSUE TITLE
How do I install this on Ubuntu 18.04?

### ISSUE THREAD

**Issue by slarrain** [projecthamster/hamster-gtk#226]
I've tried everything. With pip hamster-lib, hamster-gtk, nothing seems to work. There used to be a hamster-applet package on apt, but not anymore. I really miss using hamster. Is an awesome piece of software. 
Any help will be more than welcomed.
Thanks!

**Comment by elbenfreund** [comment]
Hi @slarrain  thanks for reaching out. Can you be more specific than
> With pip hamster-lib, hamster-gtk, nothing seems to work.
Did you follow the instructions given in the readme? What did not work? what happend instead?

Please note: `legacy hamster`, which is what was shipped with earlier ubunu versions can be found [here](https://github.com/projecthamster/hamster). An issue discussing ways to get it to run under ubuntu 18 can be found in the [issue tracker](https://github.com/projecthamster/hamster/issues/356).

**Comment by slarrain** [comment]
Hi @elbenfreund 
Thank you so much for the link to the issue #[356](https://github.com/projecthamster/hamster/issues/356). That is exactly what I was looking for and following those instructions allowed me to install it and run it on my Ubuntu 18.04.
Thanks for pointing me in the right direction and therefore I'm closing this issue since it has been resolved.

**Comment by elbenfreund** [comment]
Your're welcome :) 
Happy hamster'ing

**Comment by holderl5** [comment]
All,

I haven't tried to do this on 19.04, I opted for docker instead.  Just adding this comment to get the word out:
https://github.com/holderl5/docker-hamster
