### ISSUE TITLE
Is the Hamster project still active?

### ISSUE THREAD

**Issue by ThomasA** [projecthamster/hamster-gtk#228]
I have used the "old" Hamster for several years and would really like to keep using it. I am trying to figure out whether I should go with the newest versions of the hamster components and invest some time in using development versions in the hope that they will mature, or if I should just start looking around for another time tracker instead.

**Comment by deivid-rodriguez** [comment]
I feel similarly. There's [this fork](https://github.com/ederag/hamster) by @ederag that seems to be getting some activity, but I'm not sure, the project seems quite dead...

**Comment by ederag** [comment]
They made a lot of progress on the new `hamster-*`.
Main development should definitely go there.

The [fork](https://github.com/ederag/hamster) mentioned by @deivid-rodriguez, 
is composed of a small fixes to the master branch (2.0-rc1);
more details in the PR https://github.com/projecthamster/hamster/pull/363,
waiting for review or perhaps transfer of legacy hamster by @elbenfreund.

It worked seamlessly with the previous hamster.db (backup first though !),
and I have been happily using it daily for about 2 months now.
The plan is to maintain it until the new stuff is stable enough.

So the project is still breathing, in my opinion.

**Comment by jtojnar** [comment]
I suppose @elbenfreund is busy with other duties; I would suggest @ederag to reach out to him via e-mail.

**Comment by deivid-rodriguez** [comment]
Yeah, reaching out busy maintainers by email is usually a good idea :+1:.

**Comment by bugz8unny69** [comment]
Did I read a issue where the maintainer/author was re-writting Hamster? Why there ~~has~~ hasn't been update?

**Comment by ederag** [comment]
@lhorace Because the rewrite is not complete yet (AFAIK), and legacy hamster did not work any longer on openSUSE leap15.

**Comment by bugz8unny69** [comment]
Exactly, I corrected my sentence above.

**Comment by ThomasA** [comment]
Thanks @ederag, I was able to get your fork up and running on my Ubuntu 18.04. The project [projecthamster](https://github.com/projecthamster/) seems inactive, unfortunately. I hope it gets going again. This is exactly the time tracking tool I need and I have not been able to find any other that quite meets my expectations.

**Comment by ederag** [comment]
@jtojnar Mail sent to @elbenfreund on monday. We'll see.

@ThomasA Thanks for the feedback. The interface changed a lot in 2.0;
I ironed it out a bit, but there are probably still rough spots,
please file issues in the fork https://github.com/ederag/hamster/issues.

**Comment by elbenfreund** [comment]
Just some short feedback. As @jtojnar suspected, live got the better of me for the past months. I apologize for the lack for the communication. Despite it's looks ``projecthamster`` is not really dead, in fact I do run ``hamster-gtk`` productively as we speak. I doubt I will be able to spend much time for the rest of the year though, but have all intension to pick up working on hamster in January.

If anybody want to help, especially with the JS bit of the shell extension, please feel free to get in touch.

**Comment by ThomasA** [comment]
Good to hear that you are still on the project @elbenfreund. Of course other things in life happen as well, and volunteer software projects cannot be our first priority all the time :-)
I would just like to say thanks for taking the initiative to keeping the only Linux time tracker that really suits my needs alive. I am afraid I cannot help out with JS, but if there is need for any Python development, I may be able to help. I am a scientific computing guy, so things involving for example databases or GUI are unfamiliar to me.
Good to hear that "new Hamster" is working. My difficulty was actually figuring out whether it was in a working state at all and which components of the new Hamster project are actually required to piece together a user experience as close to the old Hamster as possible.

**Comment by elbenfreund** [comment]
A brief update: I invited @ederag as a contributor with write access to the ``hamster`` repository.
If he is still up for it, I am confident that he will bring quite a few improvements to the repository!
:tada: 

@ThomasA careful now, I might take you up on your offer after all! :) The supposed beauty of the new hamster's modular packaging is that you should not need to worry about those dependency questions you mentioned. If we did our job right, you just run a single ``pip install hamster-gtk`` in your venv and be done with it, leaving pip to pull all required dependencies.

**Comment by ederag** [comment]
@elbenfreund Thank you very much  for giving write access to https://github.com/projecthamster/hamster.
>I am confident that he will bring quite a few improvements to the repository!

Thanks for your confidence;
though, for other readers, minimal improvements are to be expected, [no fancy promises](https://github.com/projecthamster/hamster/pull/363#issuecomment-433954772) were made.
