### ISSUE TITLE
Config changes are applied only after restart

### ISSUE THREAD

**Issue by elbenfreund** [projecthamster/hamster-gtk#57]
version: 0.10.0

Changes to the preferences are only active after restarting hamster-gtk.

Whist the main apps config attribute is in fact changed right away, it is not possible to update the backend config at runtime as of now. Once ``hamster-lib`` has been improved this should be possible.

**Comment by jtojnar** [comment]
This should be probably closed in favour of #62

**Comment by elbenfreund** [comment]
Yes, once #62 is implemented this can most likely be closed.

**Comment by elbenfreund** [comment]
Fixed by #62
