### ISSUE TITLE
Make sure hamster-gtk comforms to gnome design guidelines.

### ISSUE THREAD

**Issue by elbenfreund** [projecthamster/hamster-gtk#6]
Hamster should confirm with general gnome design/interface guidelines. In order to respect those, it would be great to have someone familiar with the relevant resources (provided below as reference).
This task does not really require any programming capabilities. Instead one would have to read into the guidelines and check where the hamster gui complies or conflicts them. Once this is documented, we can address those issues much more efficiently.

Reference:
* [https://developer.gnome.org/hig/stable/](https://developer.gnome.org/hig/stable/)

**Comment by orschiro** [comment]
You can assign me to this!

**Comment by elbenfreund** [comment]
Lovely. I invited you to the UI team.

**Comment by orschiro** [comment]
Hi Eric, 

From what I have read so far, these are my thoughts.

### Change Hamster-GTK name into Hamster
### Change Your friendly time tracker into Gnome Time Tracker
### Remove dialog window "You need to specify a name" and auto-fill the tracked activity with the a time stamp that the user can still change during the duration of the tracked activity
### Change Start Tracking button into an action dialog
![image](https://cloud.githubusercontent.com/assets/170947/17457258/98b2abe0-5bf3-11e6-9333-501895a92279.png)
### Provide a go back button to the overview window
![image](https://cloud.githubusercontent.com/assets/170947/17457264/be73c814-5bf3-11e6-89d2-cbf5b0b8ad37.png)
### Show input field after user starts tracking by clicking the action button

**Comment by elbenfreund** [comment]
On a general note: It is probably better to open new issues for the individual suggestions so discussions can stay focused on one topic. Also, it would be great if you could provide a reference to the specification you comment refers to.

**Comment by elbenfreund** [comment]
@orschiro will review our gui to evaulate gnome HID guidelines. Individual feedback will be handled in dedicated issues.

**Comment by orschiro** [comment]
Hi Eric, 

I will open new separate issues for each, good idea!

By the way, I cannot yet label issues. 

Robert

**Comment by orschiro** [comment]
Hi Eric, 

I will open new separate issues for each, good idea!

By the way, I cannot yet label issues. 

Robert
