### ISSUE TITLE
Unable to identify format

### ISSUE THREAD

**Issue by orschiro** [projecthamster/hamster-gtk#64]
Dear all, 

I wanted to add a new time entry but it was refused as being in the wrong format. 

Can someone please tell me why the following text entry is not valid?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/17290875/f15c2f6c-57e0-11e6-965e-55d262570b20.png)

**Comment by elbenfreund** [comment]
Hi Robert. Yes. ``hamster-lib`` version 0.11.1 which is used by ``hamster-gtk`` right now does not support whitespace in activity strings. The entire fact parsing has been vastly improved in ``hamster-lib 0.12.0`` which I will release until mid week. Once this has been done, all you need to do is upgrade ``hamster-lib`` in you virtualenv and ``hamster-gtk`` should use the new improved parsing out of the box.
Sorry for the inconveniene, eric.

**Comment by orschiro** [comment]
Thank you Eric!

Looking forward to the new release then. :-)

~Robert

**Comment by elbenfreund** [comment]
``hamster-lib 0.12.0`` is out since yesterday. In order to profit from it all you need to do is:
* activate your hamster-gtk virtualenv
* ``pip install -U hamster-lib
* start hamster-gtk

**Comment by orschiro** [comment]
Your user guidance to solve problems is outstanding. Thanks Eric!

It does work now with spaces. :-)

![image](https://cloud.githubusercontent.com/assets/170947/17455934/a70425c4-5bc7-11e6-84ec-fe2e9ed23b11.png)
