### ISSUE TITLE
Provide a Ubuntu Unity Icon

### ISSUE THREAD

**Issue by orschiro** [projecthamster/hamster-gtk#65]
Dear all, 

Is it possible to provide an icon file that can be displayed in Ubuntu Unity?

![image](https://cloud.githubusercontent.com/assets/170947/17455939/cffd7ade-5bc7-11e6-8935-85314dc0fc5c.png)

![image](https://cloud.githubusercontent.com/assets/170947/17455941/d6c260e6-5bc7-11e6-8e78-d25443647b68.png)

![image](https://cloud.githubusercontent.com/assets/170947/17455945/e4a96024-5bc7-11e6-98e0-7b78e1612de5.png)

**Comment by elbenfreund** [comment]
Yes, there will be icons at some later stage (1.0.0 the latests). If special care is required for unity will have to be investigated. Its not a high priority at this point though.

**Comment by orschiro** [comment]
Alright, thanks for taking care of it!

**Comment by jtojnar** [comment]
Unity respects [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/) like GNOME Shell does. See #200
