### ISSUE TITLE
It should be possibe to edit an ``ongoing fact``.

### ISSUE THREAD

**Issue by orschiro** [projecthamster/hamster-gtk#68]
It should be possible to click on an entry to rename it. 

![image](https://cloud.githubusercontent.com/assets/170947/17461465/9f50c64a-5c8d-11e6-9cd4-55ed6f23f239.png)

Reference: https://hyp.is/5U04iFx8EeaT9IfSFJtrhA/developer.gnome.org/hig/stable/design-principles.html.en

**Comment by jtojnar** [comment]
Duplicate of #33
