### ISSUE TITLE
Trigger "Start Tracking" with Enter

### ISSUE THREAD

**Issue by orschiro** [projecthamster/hamster-gtk#69]
Dear all, 

It would enhance the user experience, if we support to start tracking a task by confirming with the Enter/Return keyboard button. 

What do you think?

Warmly,

~Robert

**Comment by elbenfreund** [comment]
Yes. Right now none of the shortcuts used by the ``legacy hamster`` are supported. So please feel encouraged to open a new issue for any old one thats missing or new one you feel that could be useful.
