### ISSUE TITLE
Hamster GTK does not show up in window task switcher

### ISSUE THREAD

**Issue by orschiro** [projecthamster/hamster-gtk#70]
Dear all, 

I just noticed that Hamster GTK does not show up in the window task switcher of Ubuntu Unity. 

Warmly,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/17662764/4b0b8398-62e8-11e6-9c0d-205a14b31fd9.png)

**Comment by elbenfreund** [comment]
Interesting. It does work on debian testing. Without a proper logo (none has been assigned to the application for now) but just a placeholder, but the general mechanics seem to work.

**Comment by orschiro** [comment]
Huh? Very weird. I re-opened Hamster after a few hours and now it appears as well with a generic logo!

Well, problem solved for now. 

![image](https://cloud.githubusercontent.com/assets/170947/17673323/d856984a-6320-11e6-9b3d-3e133b8b0e1f.png)
