### ISSUE TITLE
'&' in title results in empty fact-string

### ISSUE THREAD

**Issue by riker09** [projecthamster/hamster-gtk#78]
When putting an XML enitity like & (ampersand) in the title the UI crashes with this error message:

    (hamster-gtk:17884): Gtk-WARNING **: Failed to set text 'Meet & Greet - not categorised' from markup due to error parsing markup: Fehler in Zeile 1: Entität endete nicht mit einem Semikolon; wahrscheinlich haben Sie ein »&«-Zeichen verwendet, ohne eine Entität beginnen zu wollen - umschreiben Sie das »&« als »&amp;«

Seems like the ampersand wasn't encoded correctly. At least that is what the german error message is complaining about.

**Comment by elbenfreund** [comment]
Thank you for reporting this.
What were you doing when this happened exactly? Did you start a new ongoing fact? save? just load an existing db?

**Comment by riker09** [comment]
Yes, this is exactly how I reproduced the bug. I thought the UI crashed, maybe I closed the window by accident. When reproducing the issue today I experienced the same behavoir: UI _DIDN'T_ crash, but the fact-string was empty.

Interesting: When navigating through the dates (Earlier & Later) the error message on the cli still has the full fact-string, so it must be saved to the db. The issue seems to be with the display of the string.

**Comment by elbenfreund** [comment]
Yes. This is most likely some GTK.Label Related nonsense. If there would be an issue with parsing and saving the fact ``hamster-lib`` would most likely have raised an Error right there.
I will try to look into this today, but right now my main work is with the gnome-shell-extension.
Whatever the bugfix is, it is scheduled for ``hamster-gtk 0.11.0``, so it shouldn't take too long.
And of cause, PRs are always welcome. :)

**Comment by riker09** [comment]
I would love to get my hands dirty with a native app for a change (web developer here). Unfortunately I'm a complete noob on this field. Not a very helpful post, I know... :grin:

**Comment by riker09** [comment]
I did a quick search in google for GTK label, here's what I came up with:

> The markup passed to the set_markup() method must be valid. For example, the literal <>& characters must be escaped as &lt;, &gt;, and &amp;. If you pass text obtained from the user, file, or a network to the set_markup() method, you'll want to escape it with the Python Library xml.sax.saxutils.escape() function.

So I guess it's either saving the user input as an escaped string or escaping the user input upon rendering.

**Comment by elbenfreund** [comment]
Thanks for the research! :) I will most likely opt for the second option as I this is more a quirk of GTK that should not impact our underlying datastructure/storage.
