### ISSUE TITLE
Poor contrast for date colour in Overview with dark themes.

### ISSUE THREAD

**Issue by elbenfreund** [projecthamster/hamster-gtk#93]
The date label specified a light background colour but used a default foreground colour. Dark themes use light foreground colour, making the label unreadable due to a poor contrast.

**Comment by jtojnar** [comment]
This could probably be fixed by using [theme’s colours](https://github.com/GNOME/gtk/blob/gtk-3-20/gtk/theme/Adwaita/_colors-public.scss) directly but I am not sure how portable that is. As long as we are hardcoding backgrounds we should also hardcode foregrounds.
